name: Packages

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSHPASS: ${{ secrets.SSHPASS }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install fakeroot cmake cmake-data texinfo libtool-bin
    - name: Prepare Build
      run: |
        bash ./travis_prepare.sh
    - name: Build packages
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$(pwd)/../vita-makepkg:$VITASDK/bin:$PATH
        bash ./travis_build.sh
        bash ./travis_upload.sh